name: Email Address GitHub Action

# Trigger the workflow on push and pull request events
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Manual trigger option
  workflow_dispatch:

jobs:
  test:
    name: Test Job with Email
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Required step with your email address in the name
      - name: 22f3002460@ds.study.iitm.ac.in
        run: echo "Hello, world!"
